using System.Text.Json.Serialization;

namespace SourceApi.Model;

/// <summary>
/// Different modi operandi for how to generate the frequency.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FrequencyMode
{
    /// <summary>
    /// The frequency is generated by the source on the basis of a quartz clock.
    /// </summary>
    SYNTHETIC = 0,

    /// <summary>
    /// The frequency is specified by the power supply, e.g. 50Hz.
    /// </summary>
    GRID_SYNCHRONOUS = 1,

    // <summary>
    // One third of frequency is specified by the power supply, e.g. 16 2/3Hz.
    // </summary>
    THIRD_OF_GRID_SYNCHRONOUS = 2
}